export default [
  {key:'twig', name:'Twig'},
  {key:'pine', name:'Pine'},
  {key:'birch', name:'Birch'},
  {key:'poplar', name:'Poplar'},
  {key:'cedar', name:'Cedar'},
  {key:'walnut', name:'Walnut'},
  {key:'chestnut', name:'Chestnut'},
  {key:'baobab', name:'Baobab'},
  {key:'copper', name:'Copper Ore'},
  {key:'iron', name:'Iron Ore'},
  {key:'mythril', name:'Mythril Ore'},
  {key:'anchovy', name:'Anchovy'},
  {key:'sardine', name:'Sardine'},
  {key:'trout', name:'Trout'},
  {key:'salmon', name:'Salmon'},
  {key:'catfish', name:'Catfish'},
  {key:'tuna', name:'Tuna'},
  {key:'swordfish', name:'Swordfish'},
  {key:'shark', name:'Shark'},
  {key:'manta', name:'Manta Ray'},
  {key:'angler', name:'Anglerfish'},
  {key:'silver', name:'Silver Ore'},
  {key:'goldOre', name:'Gold Ore'},
  {key:'platinum', name:'Platinum Ore'},
  {key:'titanium', name:'Titanium Ore'},
  {key:'uranium', name:'Uranium Ore'},
  {key:'diamond', name:'Diamond'},
  {key:'copperBar', name:'Copper Bar'},
  {key:'ironBar', name:'Iron Bar'},
  {key:'silverBar', name:'Silver Bar'},
  {key:'goldBar', name:'Gold Bar'},
  {key:'platinumBar', name:'Platinum Bar'},
  {key:'titaniumBar', name:'Titanium Bar'},
  {key:'uraniumBar', name:'Uranium Bar'},
  {key:'diamondBar', name:'Diamond Bar'},
  {key:'copperPickaxe', name:'Copper Pickaxe'},
  {key:'copperAxe', name:'Copper Axe'},
  {key:'ironPickaxe', name:'Iron Pickaxe'},
  {key:'ironAxe', name:'Iron Axe'},
  {key:'silverPickaxe', name:'Silver Pickaxe'},
  {key:'silverAxe', name:'Silver Axe'},
  {key:'goldPickaxe', name:'Gold Pickaxe'},
  {key:'goldAxe', name:'Gold Axe'},
  {key:'platinumPickaxe', name:'Platinum Pickaxe'},
  {key:'platinumAxe', name:'Platinum Axe'},
  {key:'titaniumPickaxe', name:'Titanium Pickaxe'},
  {key:'titaniumAxe', name:'Titanium Axe'},
  {key:'uraniumPickaxe', name:'Uranium Pickaxe'},
  {key:'uraniumAxe', name:'Uranium Axe'},
  {key:'diamondPickaxe', name:'Diamond Pickaxe'},
  {key:'diamondAxe', name:'Diamond Axe'},
  {key:'fish', name:'Fish'},
  {key:'meal', name:'Meal'},
  {key:'gem', name:'Gem'},
  {key:'skin', name:'Hide'},
  {key:'wheat', name:'Wheat'},
  {key:'barley', name:'Barley'},
  {key:'oat', name:'Oat'},
  {key:'apple', name:'Apple'},
  {key:'tomato', name:'Tomato'},
  {key:'carrot', name:'Carrot'}
];
