export default [
  {key:'twig', name:'Twig'},
  {key:'pine', name:'Pine'},
  {key:'birch', name:'Birch'},
  {key:'poplar', name:'Poplar'},
  {key:'cedar', name:'Cedar'},
  {key:'walnut', name:'Walnut'},
  {key:'chestnut', name:'Chestnut'},
  {key:'baobab', name:'Baobab'},
  {key:'copper', name:'Copper Ore'},
  {key:'iron', name:'Iron Ore'},
  {key:'mythril', name:'Mythril Ore'},
  {key:'anchovy', name:'Anchovy'},
  {key:'sardine', name:'Sardine'},
  {key:'trout', name:'Trout'},
  {key:'salmon', name:'Salmon'},
  {key:'catfish', name:'Catfish'},
  {key:'tuna', name:'Tuna'},
  {key:'swordfish', name:'Swordfish'},
  {key:'shark', name:'Shark'},
  {key:'manta', name:'Manta Ray'},
  {key:'angler', name:'Anglerfish'},
  {key:'silver', name:'Silver Ore'},
  {key:'goldOre', name:'Gold Ore'},
  {key:'platinum', name:'Platinum Ore'},
  {key:'titanium', name:'Titanium Ore'},
  {key:'uranium', name:'Uranium Ore'},
  {key:'diamond', name:'Diamond'},
  {key:'fish', name:'Fish'},
  {key:'bar', name:'Metal Bar'},
  {key:'meal', name:'Meal'},
  {key:'gem', name:'Gem'},
  {key:'skin', name:'Hide'},
  {key:'wheat', name:'Wheat'},
  {key:'barley', name:'Barley'},
  {key:'oat', name:'Oat'},
  {key:'apple', name:'Apple'},
  {key:'tomato', name:'Tomato'},
  {key:'carrot', name:'Carrot'}
];
